config/routes.rb
RedmineApp::Application.routes.draw do
    match '/projects/:project_id/issues/graph', :controller => 'issues', :action => 'graph'
    match '/projects/issues/graph', :controller => 'issues', :action => 'graph', :project_id => nil
    match '/issues/:id/graph', :controller => 'issues', :action => 'graph_issue'
end

app/views/issues/_graph_link.erb
<script type="text/javascript">
  function open_issues_graph() {
    var url = "<%= url_for :controller => 'issues', :action => 'graph', :project_id => @project %>"// + '?' + $('query_form').serialize();
    var old_url = $('query_form').getAttribute('action')
    var new_window = window.open('','relationgraphpopup','height=500,width=600,resizable=yes,scrollbars=yes,toolbar=no,status=no');
    $('query_form').setAttribute('action', url)
    $('query_form').setAttribute('target', 'relationgraphpopup')
    $('query_form').submit()
    $('query_form').setAttribute('action', old_url)
    $('query_form').removeAttribute('target')
    if (window.focus) { new_window.focus() }
  }
  var link = "<%= escape_javascript link_to_function l(:build_graph), "open_issues_graph()", :class => 'icon icon-summary' %>";
  $$('#query_form .buttons.hide-when-print').first().insert({bottom: link});
</script>

app/views/issues/_show_grap_link.html.erb
<script type="text/javascript">
  function open_issue_graph() {
    var url = "<%= url_for :controller => 'issues', :action => 'graph_issue' %>"
    var new_window = window.open(url,'relationgraphpopup','height=500,width=600,resizable=yes,scrollbars=yes,toolbar=no,status=no');
    if (window.focus) { new_window.focus() }
    return false;
  }
</script>
| <%= link_to_function l(:build_graph), "open_issue_graph(); ", :class => 'icon icon-summary' %>

app/views/issues/graph.html.erb
<style type="text/css">
#graph-legend {
  position: fixed;
  bottom: 0;
  background: #fff;
  border: 1px solid #000;
}
#graph-legend.on-left {
  left: 0;
}
#graph-legend.on-right {
  right: 0;
}

#graph-legend ul {
  list-style: none;
  padding: 0;
}
#graph-legend ul li {
  vertical-align: middle;
  padding: 5px;
  clear: both;
}

#graph-legend ul li span {
  vertical-align: middle;
  font: normal 12px arial;
}

#graph-legend ul li img {
  vertical-align: middle;
}
</style>
<div id="graph-legend" class="on-right">
  <ul style="list-style: none">
    <li><%= image_tag 'red_arrow.png', :plugin => 'redmine_relations_graph' %><span> — Open Blocker</span></li>
    <li><%= image_tag 'blue_arrow.png', :plugin => 'redmine_relations_graph' %><span> — Closed Blocker</span></li>
    <li><%= image_tag 'green_arrow.png', :plugin => 'redmine_relations_graph' %><span> — SubTask</span></li>
    <li><%= image_tag 'bold_issue.png', :plugin => 'redmine_relations_graph' %><span> — Issue from request</span></li>
    <li><%= image_tag 'thin_issue.png', :plugin => 'redmine_relations_graph' %><span> — Related issue</span></li>
  </ul>
</div>
<div>
<% @graphs.each do |graph| %>
  <div style="float: left">
    <img src="data:image/png;base64,<%= Base64.encode64(graph[:png]) %>" usemap="#issuerelationsgraph<%= graph[:number] %>"/>
    <%= graph[:map].html_safe %>
  </div>
<% end %>
</div>

<script type="text/javascript">
$('map area').on('click', function(event) {
    var id = /#(\d+)/.exec(this.attributes['href'].value)[1];
    window.open('<%= issues_path %>/' +  id, '_blank')
  });
$('#graph-legend').on('mousemove', function(event) {
  var element = $(event.target);
  if (element.hasClass('on-left')) {
    element.removeClass('on-left');
    element.addClass('on-right');
  } else {
    element.removeClass('on-right');
    element.addClass('on-left');
  }
});

</script>

app/views/layouts/popup.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title><%=h html_title %></title>
    <%= javascript_heads %>
    <%= yield :header_tags -%>
  </head>
  <body>
    <%= yield %>
  </body>
</html

app/views/settings/_relations_graph.html.erb
<% defaults = Redmine::Plugin::registered_plugins[:redmine_relations_graph].settings[:default] %>
<p>
  <label>Maximum depth:</label>
  <%= text_field_tag("settings[max_depth]", @settings["max_depth"] || defaults["max_depth"]) %>
</p>